# **Part 1 - Creating the Colab Notebook**
## **Step 1** - Access your Google Drive and create a folder to store your Colab Notebooks.
## **Step 2** - Instantiate a Google Colab Notetbook and place it in the Colab Notebook file.
## **Step 3** - Download the raw public health dataset as a csv file, https://uncch.instructure.com/courses/79778/files/9979460?wrap=1 .
## **Step 4** - Insert the downloaded csv file into the Colab Notebook.

# **Part 2** - Importing and Mounting
## **Step 1** - Input the import and mount statements with your google drive as the parameter in the exact format as the lines of code provided below.
## **Step 2** - Select the files button in the left sidebar to access your google drive.

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

# **Part 3** - Importing Pandas and Numpy
## **Step 1** - Using the exact import statements provided in the lines of code below to import the pandas and numpy functions that will allow you to create data structures for analyzation of formatted tabular data and perfrom algebraic operations.

In [2]:
import pandas as pd
import numpy as np

# **Part 4** - Importing a CSV File
## **Step 1**- Name the csv file object that you will be instantiating, below I named mine data.
## **Step 2** - Next to the name of this object insert the folling segment of code: =pd.read_csv .
## **Step 3** - After the segment of code you inserted in the previous step you will insert a pair of parantheses with a pair of quotation marks in it.
## **Step 4** - Within the quotation marks referenced above insert the following code: /content/gdrive/MyDrive/Colab Notebooks/Name of CSV file .

In [3]:
data=pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/CountyHealthData_2014-2015 (1).csv')

# **Part 5** - Filetering the Pacific Data
## **Step 1** - Type the name of the csv file object followed by the opening og a square bracket.
## **Step 2** - Repeat the above step next to the code you wrote in the previous step.
## **Step 3** - In a pair of quotation marks type the word Division, to isolate the data from the Division coloumn in the raw data set.
## **Step 4** - Insert a closing square bracket.
## **Step 5** - Type a double equal sign and a pair of quotation marks on this line with Pacific within the quotation marks, to isolate all of the rows of raw data in the Pacific division.
## **Step 6** - Insert a final closing square bracket for this line of code.

In [4]:
data[data["Division"]=="Pacific"]

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
0,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2014,NaN,0.122,...,NaN,0.374,0.250,3791.0,0.185,216.0,69192,0.127,NaN,0.287
1,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2015,NaN,0.122,...,NaN,0.314,0.176,4837.0,0.185,254.0,74088,0.133,NaN,NaN
2,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2014,6827.0,0.125,...,15.37,0.218,0.096,6588.0,0.119,135.0,71094,0.319,6.29,0.160
3,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2015,6856.0,0.125,...,17.08,0.227,0.123,6582.0,0.119,148.0,76362,0.334,5.60,NaN
4,AK,West,Pacific,Bethel Census Area,2050,2050,Insuff Data,1/1/2014,13345.0,0.211,...,NaN,0.394,0.124,5860.0,0.200,169.0,41722,0.668,12.77,0.477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5804,WA,West,Pacific,Whatcom County,53073,53073,Region 22,1/1/2015,4972.0,0.114,...,10.88,0.219,0.069,7307.0,0.138,67.0,51119,0.318,2.20,NaN
5805,WA,West,Pacific,Whitman County,53075,53075,Region 22,1/1/2014,4342.0,0.095,...,4.28,0.181,0.071,8551.0,0.091,43.0,32276,0.243,NaN,0.156
5806,WA,West,Pacific,Whitman County,53075,53075,Region 22,1/1/2015,4123.0,0.095,...,4.83,0.175,0.061,8123.0,0.091,47.0,42702,0.268,NaN,NaN
5807,WA,West,Pacific,Yakima County,53077,53077,Region 22,1/1/2014,7679.0,0.220,...,8.61,0.341,0.090,8025.0,0.175,71.0,43428,0.642,7.82,0.201
5808,WA,West,Pacific,Yakima County,53077,53077,Region 22,1/1/2015,6963.0,0.220,...,8.89,0.345,0.081,8104.0,0.175,71.0,41918,0.696,8.10,NaN

# **Part 6** - Creating a Subset for the Filtered Pacific Division Data
## **Step 1** - Write a name for the subset object that will store the filtered pacific divion and add an underscore followed by the word Subset.
## **Step 2** - Insert an equal sign and the exact same line of code as it was given in the previous part.

In [5]:
Pacific_Subset=data[data["Division"]=="Pacific"]

# **Part 7**- Converting the filtered subset into a CSV file
## **Step 1** - Type the name you instantiated the filtered Pacific division data as.
## **Step 2** - Next to thi code inert a the following code: to_csv("", ).
## **Step 3** - Within the quotation marks inert the following statement which will be the name of the csv file: Pacific_Subset.csv .
## **Step 4** - Finally after the comma within the parantheses type the follwing statement: index=False .

In [6]:
Pacific_Subset.to_csv("Pacific_Subset.csv", index=False)